### ISSUE TITLE
Problem with JSON

### ISSUE THREAD

**Issue by DocKali** [lorenzoromani1983/DueDiligence#1]
Hi there,

I'm trying to run your tool, no problem for installing but when I try to run DD.py, I obtain the following message :

```
Traceback (most recent call last):
  File "DD.py", line 45, in <module>
    left = json.loads(data)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any idea where it comes from ?

Thanks for your help !

**Comment by lorenzoromani1983** [comment]
Hi!
Did you type your Zenserp token at the beginning of the file?
Maybe Zenserp changed the json structure. I'll check it out tomorrow. 
Bye

**Comment by lorenzoromani1983** [comment]
Perhaps I just checked the code again; everything is working smoothly on my side. Could you tell which configuration are you using? It requires python3 installed with the libraries in the file requirements.txt; and a working Zenserp token of course.
l.
